name: dropsource_utils
description: A set of useful functions and libraries used in almost all
  Dropsource flutter apps.
version: 0.0.3+5
author: Nathan Frechette<nate@dropsource.com>
homepage: https://dropsource.com

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  build_context: ^2.0.4
  dio: ^3.0.10
  equatable: ^1.2.5
  firebase_analytics: ^7.0.1
  firebase_core: ^0.7.0
  firebase_crashlytics: ^0.4.0+1
  flutter_email_sender: ^4.0.0

  intl: ^0.17.0
  logging: ^1.0.0
  provider: ^4.3.3
  rxdart: ^0.25.0
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
