name: ds_ui
description: A set of useful functions and libraries used in almost all
  Dropsource flutter apps.
version: 0.0.4+1
homepage: https://dropsource.com
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: 3.19.1

dependencies:
  auto_size_text: ^3.0.0
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  go_router: ^13.2.1
  intl: ^0.18.1
  logger: ^2.1.0
  ms_map_utils: ^1.1.0
  riverpod_annotation: ^2.3.5
  sentry_flutter: ^7.18.0
  url_launcher: ^6.2.5

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
